name: Release Mobile Artifacts

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (ignored on normal tag push)'
        required: false

jobs:
  build-release:
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: '3.24.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Show Flutter version
        run: flutter --version

      - name: Checkout specified tag (manual trigger)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.tag != '' }}
        run: |
          git fetch --tags --force
          if git rev-parse --verify --quiet "${{ inputs.tag }}"; then
            echo "Checking out existing tag ${{ inputs.tag }}";
            git checkout ${{ inputs.tag }}
          else
            echo "Tag ${{ inputs.tag }} not found" >&2
            exit 1
          fi

      - name: Flutter pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --no-pub

      # Optional signing if secrets provided
      - name: Prepare keystore (optional)
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          if [ -n "$KEYSTORE_BASE64" ]; then
            echo "Writing keystore from secret"
            echo "$KEYSTORE_BASE64" | base64 -d > android/app/upload-keystore.jks
          else
            echo "No keystore secret provided; skipping signing.";
          fi

      - name: Build release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Build release App Bundle (AAB)
        run: flutter build appbundle --release --no-tree-shake-icons

      - name: Archive artifacts
        run: |
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/app-release.apk artifacts/
          cp build/app/outputs/bundle/release/app-release.aab artifacts/
          echo "Artifacts prepared"

      - name: Determine tag name
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ inputs.tag }}" ]; then
            echo "TAG=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/app-release.apk
            artifacts/app-release.aab
          generate_release_notes: true
          tag_name: ${{ steps.vars.outputs.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload individual artifacts (backup)
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: artifacts/*
          if-no-files-found: error
