name: Release Mobile Artifacts

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (ignored on normal tag push)'
        required: false

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --no-pub

      # Optional signing if secrets provided
      - name: Prepare keystore (optional)
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > android/app/upload-keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Build release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Build release App Bundle (AAB)
        run: flutter build appbundle --release --no-tree-shake-icons

      - name: Archive artifacts
        run: |
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/app-release.apk artifacts/
          cp build/app/outputs/bundle/release/app-release.aab artifacts/
          echo "Artifacts prepared"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/app-release.apk
            artifacts/app-release.aab
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload individual artifacts (backup)
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: artifacts/*
          if-no-files-found: error
